/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUI;

import Domain.Driver;  
import Techserv.DriverDA;
import java.util.ArrayList;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Sezan Ahmed
 */
public class Main extends javax.swing.JFrame {

  private DriverDA driverDA;
  /**
   * Creates new form Main
   */
  public Main() {
    driverDA = new DriverDA();
    initComponents();
    updateTable();
    resetEditMode();
    clearForm();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Add = new javax.swing.JButton();
    Update = new javax.swing.JButton();
    Delete = new javax.swing.JButton();
    Next = new javax.swing.JButton();
    Previous = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    Table = new javax.swing.JTable();
    Name = new javax.swing.JLabel();
    NameField = new javax.swing.JTextField();
    ID = new javax.swing.JLabel();
    IDField = new javax.swing.JTextField();
    ContactNo = new javax.swing.JLabel();
    ContactNoField = new javax.swing.JTextField();
    Address = new javax.swing.JLabel();
    AddressField = new javax.swing.JTextField();
    AddInformation = new javax.swing.JButton();
    DeleteInformation = new javax.swing.JButton();
    UpdateInformation = new javax.swing.JButton();
    Reset = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    Add.setText("Add");
    Add.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AddActionPerformed(evt);
      }
    });

    Update.setText("Update");
    Update.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        UpdateActionPerformed(evt);
      }
    });

    Delete.setText("Delete");
    Delete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DeleteActionPerformed(evt);
      }
    });

    Next.setText("Next");
    Next.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        NextActionPerformed(evt);
      }
    });

    Previous.setText("Previous");
    Previous.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        PreviousActionPerformed(evt);
      }
    });

    Table.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Name", "ID", "Contact No", "Address"
      }
    ));
    jScrollPane1.setViewportView(Table);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        .addContainerGap())
    );

    Name.setText("Name:");

    ID.setText("ID:");

    IDField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        IDFieldActionPerformed(evt);
      }
    });

    ContactNo.setText("Contact No:");

    ContactNoField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ContactNoFieldActionPerformed(evt);
      }
    });

    Address.setText("Address:");

    AddInformation.setText("Add Information");
    AddInformation.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AddInformationActionPerformed(evt);
      }
    });

    DeleteInformation.setText("Delete Information");
    DeleteInformation.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DeleteInformationActionPerformed(evt);
      }
    });

    UpdateInformation.setText("Update Information");
    UpdateInformation.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        UpdateInformationActionPerformed(evt);
      }
    });

    Reset.setText("Reset");
    Reset.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ResetActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(Reset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Next, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Previous, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(ID)
                  .addComponent(Address)
                  .addComponent(Name))
                .addGap(25, 25, 25))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(NameField)
                  .addComponent(IDField)
                  .addComponent(ContactNoField)
                  .addComponent(AddressField))
                .addGap(247, 247, 247))
              .addGroup(layout.createSequentialGroup()
                .addComponent(AddInformation)
                .addGap(18, 18, 18)
                .addComponent(DeleteInformation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(165, 165, 165)
            .addComponent(UpdateInformation)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(Name))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(ID))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(ContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(ContactNo))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(Address))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(AddInformation)
              .addComponent(DeleteInformation))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(UpdateInformation)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33)))
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
    clearForm();
    Add.setEnabled(false);
    Delete.setEnabled(false);
    Update.setEnabled(false);
    Next.setEnabled(false);
    Previous.setEnabled(false);
    AddInformation.setEnabled(false);
    DeleteInformation.setEnabled(false);
    UpdateInformation.setEnabled(true);
    fieldEditable(true);
  }//GEN-LAST:event_UpdateActionPerformed

  private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

    clearForm();
    Add.setEnabled(false);
    Delete.setEnabled(false);
    Update.setEnabled(false);
    Next.setEnabled(false);
    Previous.setEnabled(false);
    AddInformation.setEnabled(true);
    DeleteInformation.setEnabled(false);
    UpdateInformation.setEnabled(false);
    fieldEditable(true);
    
  }//GEN-LAST:event_AddActionPerformed

  private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
    nextDriver();
  }//GEN-LAST:event_NextActionPerformed

  private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_IDFieldActionPerformed

  private void ContactNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNoFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ContactNoFieldActionPerformed

  private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
    clearForm();
    Add.setEnabled(false);
    Update.setEnabled(false);
    Delete.setEnabled(false);
    Next.setEnabled(false);
    Previous.setEnabled(false);
    AddInformation.setEnabled(false);
    DeleteInformation.setEnabled(true);
    UpdateInformation.setEnabled(false);
    NameField.setEditable(false);
    ContactNoField.setEditable(false);
    AddressField.setEditable(false);
    IDField.setEditable(true);
  }//GEN-LAST:event_DeleteActionPerformed

  private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
    prevDriver();
  }//GEN-LAST:event_PreviousActionPerformed

  private void AddInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInformationActionPerformed
    driverDA.addDriver(new Driver(
                       IDField.getText(),
                       NameField.getText(),
                       ContactNoField.getText(),
                       AddressField.getText()
                      ));
    updateTable();
    resetEditMode();
    clearForm();
    JOptionPane.showMessageDialog(this, "Successfully Performed Action!");
  }//GEN-LAST:event_AddInformationActionPerformed

  private void DeleteInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteInformationActionPerformed
    driverDA.deleteDriver(IDField.getText());
    updateTable();
    resetEditMode();
    clearForm();
    JOptionPane.showMessageDialog(this, "Successfully Performed Action!");
  }//GEN-LAST:event_DeleteInformationActionPerformed

  private void UpdateInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInformationActionPerformed
    driverDA.updateDriver(IDField.getText(), new Driver(
                       IDField.getText(),
                       NameField.getText(),
                       ContactNoField.getText(),
                       AddressField.getText()
                      ));
    updateTable();
    resetEditMode();
    clearForm();
    JOptionPane.showMessageDialog(this, "Successfully Performed Action!");
  }//GEN-LAST:event_UpdateInformationActionPerformed

  private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
    fieldEditable(true);
    resetEditMode();
    clearForm();
  }//GEN-LAST:event_ResetActionPerformed
  
  private void resetEditMode() {
    Add.setEnabled(true);
    Delete.setEnabled(true);
    Update.setEnabled(true);
    Next.setEnabled(true);
    Previous.setEnabled(true);
    AddInformation.setEnabled(false);
    DeleteInformation.setEnabled(false);
    UpdateInformation.setEnabled(false);
    updateTable();
    fieldEditable(false);
  }
  
  private void clearForm() {
    fieldEditable(true);
    NameField.setText("");
    IDField.setText("");
    ContactNoField.setText("");
    AddressField.setText("");
    fieldEditable(false);
  }
  
  private void updateTable() {
    driverDA.populateDriverList();
    ArrayList<Driver> current = driverDA.getDriverList();
    while(Table.getRowCount() > 0) {
      ((DefaultTableModel) Table.getModel()).removeRow(0);
    }
    for(int i = 0; i < current.size(); i++) {
      Object[] row = new Object[4];
      row[0] = current.get(i).getDriverName();
      row[1] = current.get(i).getDriverID();
      row[2] = current.get(i).getContactNo();
      row[3] = current.get(i).getAddress();
      ((DefaultTableModel) Table.getModel()).addRow(row);
    }
  }
  
  private void updateDriverForm() {
    Driver current = driverDA.getCurrentDriver();
    NameField.setText(current.getDriverName());
    IDField.setText(current.getDriverID());
    ContactNoField.setText(current.getContactNo());
    AddressField.setText(current.getAddress());
  }
  
  private void fieldEditable(boolean flag) {
    NameField.setEditable(flag);
    IDField.setEditable(flag);
    ContactNoField.setEditable(flag);
    AddressField.setEditable(flag);
  }
  
  private void nextDriver() {
    driverDA.getNextDriver();
    updateDriverForm();
  }
  
  private void prevDriver() {
    driverDA.getPreviousDriver();
    updateDriverForm();
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Add;
  private javax.swing.JButton AddInformation;
  private javax.swing.JLabel Address;
  private javax.swing.JTextField AddressField;
  private javax.swing.JLabel ContactNo;
  private javax.swing.JTextField ContactNoField;
  private javax.swing.JButton Delete;
  private javax.swing.JButton DeleteInformation;
  private javax.swing.JLabel ID;
  private javax.swing.JTextField IDField;
  private javax.swing.JLabel Name;
  private javax.swing.JTextField NameField;
  private javax.swing.JButton Next;
  private javax.swing.JButton Previous;
  private javax.swing.JButton Reset;
  private javax.swing.JTable Table;
  private javax.swing.JButton Update;
  private javax.swing.JButton UpdateInformation;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
